language: java
sudo: false

cache:
  directories:
    - $HOME/.m2
    
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7

script:
  - mvn clean package

notifications:
  email:
    on_success: change
    on_failure: always
  
